### ISSUE TITLE
SW-Auto-Updating not Updating due to Updater include missing

### ISSUE THREAD

**Issue by ghost** [Sarabveer/SM-Plugins#1]
I'm trying to compile it in the version of SourceMod 1.8 but the bug, could it check for me?
![sem titulo](https://user-images.githubusercontent.com/20426000/29055639-efc04856-7bd3-11e7-9f59-2041a2f006b2.png)

**Comment by sarabveer** [comment]
Download the updater.inc include file from here: https://forums.alliedmods.net/showthread.php?t=169095

Then compile.
